# Generated by Django 4.2 on 2023-07-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='children',
            new_name='parent',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
